version: '3.8'
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../src:/app/src
      - ../utils:/app/utils
      - ../public:/app/public
      - ../storage:/app/storage
      - ../routes:/app/routes
      - ../vendor:/app/vendor
      - ../composer.json:/app/composer.json
      - ../composer.lock:/app/composer.lock
    links:
      - php
    networks: 
      - int3rnal
      
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_container
    restart: always
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../routes:/app/routes
      - ../utils:/app/utils
      - ../storage:/app/storage
      - ../vendor:/app/vendor
      - ../composer.json:/app/composer.json
      - ../composer.lock:/app/composer.lock

    env_file:
      - ../.env
      - ../.env.mail
      - ./mysql/.env
    links:
      - mysql
    networks: 
      - int3rnal
      
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql_container
    restart: unless-stopped
    #volumes:
    #  - ../database/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - int3rnal

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks: 
      - int3rnal
  
networks:
  int3rnal:
    driver: bridge
    #driver_opts:
    #  com.docker.network.bridge.name: n3tw0rk
